### PR TITLE
Fix Background issues

### LINKED ISSUE #58: Background image is broken when AppBar.Prominent is changed
**Describe the bug**
The background image of Appbar(Top) is broken when I changed AppBar.Prominent

**To Reproduce**
1. Launch MaterialGallery
2. Select Appbar(Top) Gallery
3. click SET/UNSET BG button
4. click PROMINENT ON/OFF button

**Expected behavior**

**Screenshots**

### PR DESCRIPTION
**Pull request by shyunMin**
This PR is to fix BackgroundColor, BackgroundImage issues in NavigationView and MTopAppbar

Fix #58, #60 

| Appbar.Prominent = True | Appbar.Prominent = False |
|--|--|
| |  |

| NavigationView(dafult) | NavigationView.BackgroundColor = Yellow | NavigationView.BackgroundImage = photo.jpg(Tile) |
|--|--|--|
|  |  | 

**API Changes**
- removed
``` c#
public abstract class MAppBar : Background, IColorSchemeComponent, IOptionalComponent { ... }
public class MNavigationView : Background, IColorSchemeComponent, IOptionalComponent 
{
    public Image BackgroundImage
}
```

- Added
``` c#
public abstract class MAppBar : Layout, IColorSchemeComponent, IOptionalComponent { ... }
public class MNavigationView : Layout, IColorSchemeComponent, IOptionalComponent 
{
    public BackgroundOptions BackgroundOption;
    public string BackgroundImageFile
}
```

### CODE REVIEW

**Review by rookiejava — COMMENTED** [review]
do not change file mode

**Comment by shyunMin** [comment]
Fixed.

**Review by rookiejava — COMMENTED** [review]
Please explain the existing issues in more detail. As you know, `Background` is also `Layout`, so I'm curious about the reason change the base type.

**Comment by rookiejava** [comment]
This issue only occurs in f-hub.
I think it's an internal platform issue. (Of course we can bypass it, but I don't think it's an optimal solution.)

**Comment by shyunMin** [comment]
I've reported this issue to TizenFX. I will check again when I get the answer.
https://github.com/Samsung/TizenFX/issues/2010

**Pull request closed without merging**
